### ISSUE TITLE
Mismatch on last day of the simulation in checkpoint restored model

### ISSUE THREAD

**Issue by fadikar** [NSF-RESUME/covid-age#6]
Mismatch between a one-shot simulation of duration 40 vs two sequential simulations of duration 20 and 20 respectively using checkpointing:

- One shot:
` '{"random_seeds":[[0,1111]],"ini_Ki":1,"Ki_ap":[[0,0.4],[25,0.5]], "duration":40}' `
- Sequential:
 `'{"random_seeds":[[0,1111]],"ini_Ki":1,"Ki_ap":[[0,0.4],[25,0.5]], "duration":20, "save_to": "check1"}'`
`'{"random_seeds":[[0,-1]],"ini_Ki":1,"Ki_ap":[[0,0.4],[25,0.5]], "duration":20, "restore_from": "check1"}'` 

The output from above two are identical except for day 40, i.e., the last day.

**Comment by ncollier** [comment]
Reproduced on the rng_stream_work branch.

**Comment by ncollier** [comment]
This `./model '{"random_seeds":[[0,-1]], "duration":20, "restore_from": "check1"}'` also enough to reproduce the issue.

Also, commenting out in the code any changes to the deserialized node, so just straight from the archive, also reproduces the problem.

**Comment by ncollier** [comment]
Full run has more events between 39 and 40. Loop terminates with: 

`while ( (next_event_time != -1) and (next_event_time < start_time + duration) )`

Full:  `start_time, duration: 9.000, 31.000`
Continuation:  `start_time, duration: 19.990, 20.000`

Full ends at when next_event_time < 40 and continuation with 39.992. So full runs these event times:

```
Next Evt Time: 39.992
Next Evt Time: 39.992
Next Evt Time: 39.992
Next Evt Time: 39.992
Next Evt Time: 39.993
Next Evt Time: 39.996
Next Evt Time: 39.998
Next Evt Time: 39.999
```

which continuation doesn't.

On deserialization, `start_time` is set to the last `Now` value which will be the last time at which the last event executed. This may not be the full duration. Consequently, the simulation can end slightly too early. 

I've added an `offset` value (`duration - Now`) that gets serialized, and the new stopping condition is 

`while ( (next_event_time != -1) and (next_event_time < start_time + duration + offset) )`

So a deserialized run gets the offset from the previous run and uses that in its stopping condition.

**Comment by fadikar** [comment]
Continuation of continuation of continuation has the same problem. 

[commit](https://github.com/NSF-RESUME/covid-age/commit/648edff69699293db759811f8e3983df5a6dd0de)

**Comment by fadikar** [comment]
This issue is resolved.
